[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("python3")'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'tex': {
\       'command': 'latexmk',
\       'exec': ['%c -gg -pdfdvi %s', 'open -F %s:r.pdf']
\   },
\}
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'epilande/neomake-local-eslint.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = 'let g:rustfmt_autosave = 1'

[[plugins]]
repo = 'racer-rust/vim-racer'

[[plugins]]
repo = 'mhartington/nvim-typescript'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'c-brenn/phoenix.vim'

[[plugins]]
repo =  'tpope/vim-projectionist'

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
hook_add = 'let g:gutentags_cache_dir = "~/.tags_cache"'

[[plugins]]
repo = 'Shougo/vinarise.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
