[[plugins]]
repo = 'AlessandroYorba/Arcadia'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
rev = 'release'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'Shougo/vinarise.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    let g:fzf_buffers_jump = 1
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
      \   fzf#vim#with_preview({'options': '--reverse --delimiter : --nth 3..'}, 'down:40%:wrap'))
'''

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'jidn/vim-dbml'
hook_add = '''
  let g:dbml_nofold_blocks = 1
'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_linters = {
    \'markdown': ['vale'],
    \'reStructuredText': ['vale'],
    \'AsciiDoc': ['vale'],
  \ }
  let g:ale_lint_on_save = 1
'''
