[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("python3")'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'monkoose/boa.vim'

[[plugins]]
repo = 'AlessandroYorba/Arcadia'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'tex': {
\       'command': 'latexmk',
\       'exec': ['%c -gg -pdfdvi %s', 'open -F %s:r.pdf']
\   },
\}
'''
[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'epilande/neomake-local-eslint.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'mhartington/nvim-typescript'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'c-brenn/phoenix.vim'

[[plugins]]
repo =  'tpope/vim-projectionist'

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
hook_add = 'let g:gutentags_cache_dir = "~/.tags_cache"'

[[plugins]]
repo = 'Shougo/vinarise.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    let g:fzf_buffers_jump = 1
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
      \   fzf#vim#with_preview({'options': '--reverse --delimiter : --nth 3..'}, 'down:40%:wrap'))
'''
